[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
  [headers.values]
  Permissions-Policy = "accelerometer=(), autoplay=*, clipboard-write=*, encrypted-media=*, picture-in-picture=*"
  X-Frame-Options = "ALLOWALL"
